### ISSUE TITLE
Add Linea Testnet and Mainnet information to `ape-infura` plugin  [APE-1170]

### ISSUE THREAD

**Issue by dawnseeker8** [ApeWorX/ape-infura#63]
### Overview

Linea testnet has already been public released few months ago, and linea mainnet will be available soon roughly on 18th July.  
In ConsenSys, we have created a fork of this repo at [apxworx-ape-infura](https://github.com/Consensys/apeworx-ape-infura) to add the feature to this library to support `linea goerli testnet` and `linea mainnet`.

And this PR will be created soon to merge to this repo from our fork repo after we have successfully tested with linea chain.

- What you are trying to do
Add `linea testnet` and `linea mainnet` support to this plugin.
- Why Ape's current functionality is inadequate to address your goal
The current plugin doesn't include the linea chain network information.

### Specification

Following is the detail of linea network information:

| Network Name  | Linea goerli testnet | Linea Mainnet |
| ------------- | ------------- | ------------ |
| RPC URL | https://linea-goerli.infura.io/v3/<PROJECT_ID> | https://linea-mainnet.infura.io/v3/<PROJECT_ID> |
| Chain ID | 59140 | 59144 |
| Currency Symbol | ETH | ETH |
| Block Explorer URL | https://goerli.lineascan.build/ | https://explorer.linea.build/|

above information will be added to appropriate python files in this plugin.

### Dependencies

None.

**Comment by fubuloubu** [comment]
> Hi @fubuloubu @antazoey! As a side question, would you be ok if ApeWorX was listed as part of Linea's ecosystem on [linea.build](https://linea.build/) website? If so, would you have a logotype to provide? Thanks a lot for support slightly_smiling_face

Absolutely! Here are 3 different choices (middle one is black w/ transparent background):
![Apeworx_FullLogo_Green-P_black-background](https://github.com/ApeWorX/ape-infura/assets/3859395/12e9e1c6-3bd8-4c2f-b6b4-52c268024435)
![Apeworx_FullLogo_Grey-P](https://github.com/ApeWorX/ape-infura/assets/3859395/b533c00a-0a37-4092-b1b0-5ca04ad163cf)
![Apeworx_FullLogo_White](https://github.com/ApeWorX/ape-infura/assets/3859395/551eac7e-50a8-4ee0-ad33-89780bf960e6)

**Comment by Akaryatrh** [comment]
Woah gorgeous 🤩 Thanks again!

FYI @croll83

**Comment by Akaryatrh** [comment]
@fubuloubu we would like to provide you a whitelisted Infura key if you want to try out Linea mainnet before launch date. Any way to contact you privately?

**Comment by fubuloubu** [comment]
> @fubuloubu we would like to provide you a whitelisted Infura key if you want to try out Linea mainnet before launch date. Any way to contact you privately?

Hey @Akaryatrh, that sounds great! We are a bit busy at the moment, but we can create a telegram group and see if one of us has some spare time to play around with it. My handle is the same on TG

**Comment by fubuloubu** [comment]
Actually, random thought, but looking at your ecosystem plugin readme [here](https://github.com/Consensys/ape-linea/tree/main#work-in-progress) I was thinking that we could make this the first example of an "approved, community-maintained ape plugin" which is something we've been meaning to do for a while.

Think of it like the "Seal Of Approval" for plugins so people know whats top tier and what to look for (and to highlight your plugin obv).

You can actually publish the plugin today under the `ape-linea` PyPI package (I would recommend doing so soon using an alpha or beta tag). As a side note, we are matching the minor tags with ape core, so I would publish as `v0.6.0-alpha.1` or similar. The way our plugin system works, as soon as that package is published then anyone can install it, but what the "approved" plugins get is listed under `ape plugins list --all`, and since we know you all are serious about maintaining it we can trust that it is worthwhile to list as "approved" (basically, keep up with minor tag releases e.g. `v0.7.x`)

If this sounds good to you, let's definitely talk. We would love to co-market the launch with you a bit more as well!

**Comment by satyajeetkolhapure** [comment]
Hi @fubuloubu,

Although it is a good proposal to bring community owned plugins in ape plugins family, we haven’t planned for the bandwidth and resource allocation for maintaining and owning the package at this stage. Therefore we would prefer ApeWorX to own ape-linea. We will definitely think about it for future packages. We will discuss within our teams if we can allocate some bandwidth for maintaining community owned packages.

**Comment by dawnseeker8** [comment]
PR has been created for this [PR](https://github.com/ApeWorX/ape-infura/pull/64)

Please review and merged.
